---
title: "Recomendación de anuncios"
author: 
    - "Jorge Almonacid, Rubén Genillo, Humberto Pérez de la Blanca, Cristina Suárez"
    - "Universidad San Pablo CEU"

lang: es
format:
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
    toc-title: Indice
    geometry:
      - top=30mm
      - left=20mm
    documentclass: journal
    keep-tex: true
---

{{< pagebreak >}}

## Brainstorming

Durante el brainstorming, se exploraron diversas áreas de interés, desde la seguridad informática con el análisis de correos maliciosos y el desarrollo de un detector de malware, hasta la aplicación de la teoría de juegos para identificar posibles trampas, lo que representa un enfoque innovador con amplias implicaciones. Además, se abordó el campo de la inteligencia artificial con la creación de un modelo de generación de texto, lo que refleja un interés en tecnologías avanzadas y su impacto potencial.

Se seleccionó una idea centrada en el ámbito del análisis de datos en redes sociales para la recomendación de anuncios. Esta propuesta demuestra una comprensión perspicaz del papel cada vez más relevante que desempeñan las opiniones y tendencias en línea en el mundo del marketing digital.



#### Necesidades:

Al haber seleccionado la idea centrada en el análisis de datos en redes sociales para la recomendación de anuncios, se pone de manifiesto la importancia de estar actualizados, ser precisos y comprender las respuestas de los clientes. Estas necesidades reflejan la relevancia de mantenerse al tanto de las tendencias cambiantes en línea, la precisión en la interpretación de datos y la comprensión profunda de las interacciones de los clientes en entornos digitales. Este enfoque resalta la importancia estratégica del marketing en un mundo cada vez más impulsado por la información y las interacciones en línea.



## Objetivo

El objetivo de la extracción de datos y opiniones en redes sociales de usuarios para la recomendación de anuncios se fundamenta en la necesidad de acceder a información pública, en tiempo real y constantemente actualizada. Este enfoque estratégico busca aprovechar la riqueza de datos disponibles en entornos digitales públicos, garantizar la relevancia y actualidad de la información recopilada, y capturar las tendencias y opiniones más recientes. Al hacerlo, se busca informar decisiones de marketing con datos dinámicos y significativos, alineados con las demandas cambiantes del mercado y las interacciones de los usuarios en línea.


Además, este enfoque puede tener usos alternativos significativos que van más allá de la recomendación de anuncios. Por ejemplo, la extracción de datos y opiniones en redes sociales puede ser invaluable para la investigación de clientes, permitiendo una comprensión más profunda de sus necesidades, preferencias y comportamientos en línea. Asimismo, la identificación de *Brand Ambassadors*, es decir, usuarios influyentes que puedan promover de manera auténtica una marca, es otro beneficio clave de esta estrategia. Además, el manejo de reputación en línea se ve reforzado por la capacidad de monitorear y responder de manera proactiva a las interacciones en redes sociales, lo que puede impactar positivamente la percepción pública de una empresa o producto. Estos son solo algunos ejemplos de cómo este enfoque puede ser aprovechado para una variedad de aplicaciones estratégicas más allá de la publicidad y recomendaciones comerciales.



## Tareas

La tarea se puede dividir en los siguientes temas:

#### Extracción de Datos:
En esta fase, se enfocará en la extracción de datos clave de la plataforma Twitter. Se buscará obtener información pública de los usuarios, como nombres, biografías, publicaciones, día y hora de publicación, comentarios, interacciones como me gusta, seguidores, seguidos y hashtags utilizados. Esta información será recopilada a través de una API que permitirá acceder a estos datos de manera estructurada. Además, se profundizará en la obtención de información personal más detallada, como edad, género, localización, ocupación e intereses de los usuarios para enriquecer el análisis.

#### Filtrar posts relevantes:
Una vez recopilados los datos, el siguiente paso será filtrar y clasificar los posts relevantes. Para lograr esto, se implementará un análisis de temas avanzado. Se utilizarán algoritmos especializados como el Análisis Semántico Latente (LSA) y la Asignación Latente de Dirichlet (LDA) para identificar patrones y agrupar los posts según los temas principales que abordan. Este proceso permitirá segmentar la información de manera efectiva y comprender mejor las discusiones que tienen lugar en la plataforma.

#### Análisis de sentimiento:
Otro aspecto fundamental de esta tarea es el análisis de sentimiento. Aquí se enfocará en determinar la polaridad de las opiniones expresadas en los posts recopilados. Para ello, se emplearán lexicons de sentimiento que ayudarán a clasificar las opiniones como positivas, negativas o neutras. Además, se explorará un método alternativo que involucra el uso de LMQL o langchain con Large Language Models para mejorar la precisión y profundidad del análisis de sentimiento.

Se estudiarán detenidamente los datos obtenidos de Twitter para llevar a cabo estas tareas con rigor y obtener insights significativos que puedan impulsar estrategias efectivas en marketing digital y toma de decisiones empresariales.


## Diagramas




## Proyecto
